# docker-compose.yml sur Artemis
services:
  mongodb-smartcheers:
    image: mongo:latest
    container_name: mongodb-smartcheers
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
    - "127.0.0.1:27017:27017"
    volumes:
      - mongo_smartcheers_data:/data/db
    env_file:
      - .env

volumes:
  mongo_smartcheers_data:
