version: '3.8'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongodb
    restart: always
    command: [ "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mqtt_network

  mongo_secondary:
    image: mongo:latest
    container_name: mongodb_secondary
    restart: always
    command: [ "--bind_ip_all" ]
    ports:
      - "27018:27017"
    volumes:
      - ./mongo_data_secondary:/data/db
    networks:
      - mqtt_network

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/Brussels
      - NODE_RED_BIND_ADDRESS=0.0.0.0
    networks:
      - mqtt_network
    depends_on:
      - mongo

#  node-red-client:
#    image: nodered/node-red:latest
#    container_name: node-red-client
#    restart: unless-stopped
#    ports:
#      - "1880:1880"
#    volumes:
#      - ./client_data:/data
#    environment:
#      - TZ=Europe/Brussels
#    networks:
#      - mqtt_network
#    depends_on:
#      - mongo

  node-red-employee:
    image: nodered/node-red:latest
    container_name: node-red-employee
    restart: unless-stopped
    ports:
      - "1881:1880"
    volumes:
      - ./employee_data:/data
      - ./certs/employee:/certs
    environment:
      - TZ=Europe/Brussels
    networks:
      - mqtt_network
    depends_on:
      - mongo

networks:
  mqtt_network:
    driver: bridge









